[package]
name = "avida-common"
description = "Useful common types and traits for AVIDA verifiers"
edition = "2021"
version = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
