[package]
name = "ssi"
description = "Useful libraries for contracts with SSI functions"
edition = "2021"
version = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
licence-file = "LICENSE" 

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
sylvia = { workspace = true }
sylvia-derive = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
ursa = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
serde-json-wasm = { workspace = true }

